Added a new PracticeMode
daniel-lerch/vocup pull request #56
Opened 2024-04-03 16:59 UTC by jdelange22

Added an option to question both mother tongue to foreign language and reverse randomly
Fixes #53

2024-04-03 17:00 UTC, jdelange22 commented
Please note that PracticeDialog.cs is known as a binary file in the repo, probably due to incorrect file encoding. You might consider deleting this file and re-adding it using proper UTF-8 encoding.

2024-04-17 10:54 UTC, daniel-lerch requested changes
Thank you very much for this excellent contribution. I added comments for just a few details that you can change.

2024-04-17 10:54 UTC, daniel-lerch commented on src/Vocup/Forms/PracticeDialog.cs
> +            if (random.Next(100) < 50)
Since .NET 6 it is not required to create an instance of `Random` anymore.

```suggestion
            if (Random.Shared.Next(2) == 0)
```

2024-04-17 10:54 UTC, daniel-lerch commented on src/Vocup/Forms/VocabularyBookSettings.cs
> +        book.PracticeMode = RbModeAskForeignLang.Checked ? PracticeMode.AskForForeignLang : RbModeAskMotherTongue.Checked ? PracticeMode.AskForMotherTongue : PracticeMode.AskForBothMixed;
With more practice modes this line of code is hardly readable anymore. Maybe it would be clearer with a switch expression.

2024-04-17 10:54 UTC, daniel-lerch commented on src/Vocup/Models/PracticeMode.cs
> +        /// The word is either displayed in the foreign language and the user has to enter the word in the mother tongue, or the other way around.
Please mention that practice direction is mixed randomly.

2024-04-17 10:54 UTC, daniel-lerch commented on src/Vocup/Forms/PracticeDialog.cs
> +    private PracticeMode currentPracticeMode;
Please introduce a new enum `PracticeDirection` to differentiate between a practice mode which can also be random and the actual practice direction.

2024-04-19 17:42 UTC, jdelange22 commented
@daniel-lerch PR has been updated

2024-04-20 09:36 UTC, daniel-lerch approved these changes

2024-04-20 09:36 UTC, merged